# DCENT_Voice — open-source, local-first voice dictation
# Copyright (c) 2026 D-Central Technologies — decentralized technologies for digital sovereignty
# SPDX-License-Identifier: MIT
"""Brand icon loading for tray, windows, and packaging.

Assets live under ``ui/web/icons/`` (PNG + multi-size ICO) and are generated by
``scripts/render_brand_icon.py`` from the DCENT particles + waveform language.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

_ICONS_DIR = Path(__file__).resolve().parent / "web" / "icons"


def icons_dir() -> Path:
    return _ICONS_DIR


def icon_path(*names: str) -> Path | None:
    """Return the first existing path among ``names`` under the icons directory."""
    for name in names:
        path = _ICONS_DIR / name
        if path.is_file():
            return path
    return None


def load_tray_image() -> Any | None:
    """Pillow Image for pystray, or None if assets / Pillow unavailable."""
    try:
        from PIL import Image
    except ImportError:  # pragma: no cover
        return None
    path = icon_path("app-icon-64.png", "app-icon-128.png", "app-icon-256.png")
    if path is None:
        return None
    with Image.open(path) as img:
        return img.convert("RGBA").copy()


def load_window_icon_path() -> str | None:
    """Filesystem path for pywebview / OS window icons."""
    path = icon_path("app-icon-256.png", "app-icon-128.png", "app-icon.ico")
    return str(path) if path is not None else None
