# DCENT_Voice — open-source, local-first voice dictation
# Copyright (c) 2026 D-Central Technologies — decentralized technologies for digital sovereignty
# SPDX-License-Identifier: MIT
<#
.SYNOPSIS
    Render scripts\qa\DCENT_Voice.wsb with this checkout's absolute dist path.

.DESCRIPTION
    Windows Sandbox will not start a .wsb whose <HostFolder> does not exist, and
    the path is machine-specific, so the committed .wsb keeps a placeholder and
    this script produces the runnable copy under build\qa\.

.PARAMETER Source
    Folder to map read-only into the sandbox. Defaults to <repo>\dist.

.PARAMETER Output
    Destination .wsb. Defaults to <repo>\build\qa\DCENT_Voice.wsb.

.PARAMETER Networking
    Enable sandbox networking. Use for the second QA pass, which exists to
    observe SmartScreen on an unsigned Setup.exe. The default (off) is the
    offline pass that proves the app needs no network at all.

.PARAMETER Start
    Launch the generated .wsb immediately.

.EXAMPLE
    pwsh -File scripts\qa\new_sandbox.ps1 -Start
#>
[CmdletBinding()]
param(
    [string]$Source = "",
    [string]$Output = "",
    [switch]$Networking,
    [switch]$Start
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
if (-not $Source) { $Source = Join-Path $repoRoot "dist" }
if (-not $Output) { $Output = Join-Path $repoRoot "build\qa\DCENT_Voice.wsb" }

$sourceFull = [System.IO.Path]::GetFullPath($Source)
if (-not (Test-Path -LiteralPath $sourceFull -PathType Container)) {
    throw "Mapped folder does not exist: $sourceFull. Build it with scripts\build_pyinstaller.ps1 and scripts\build_installer.ps1 first."
}

$setup = Join-Path $sourceFull "DCENT_Voice-Setup.exe"
if (-not (Test-Path -LiteralPath $setup)) {
    Write-Warning "No DCENT_Voice-Setup.exe in $sourceFull; the sandbox will have nothing to install."
}

$template = Join-Path $PSScriptRoot "DCENT_Voice.wsb"
$xml = Get-Content -LiteralPath $template -Raw -Encoding UTF8

# Drop the template's own instructions; the generated file needs a header that
# says where it came from, not how to generate it.
$xml = [regex]::Replace($xml, "(?s)<!--.*?-->", @"
<!--
  GENERATED by scripts\qa\new_sandbox.ps1 - do not edit; regenerate instead.
  Template:  scripts\qa\DCENT_Voice.wsb
  Checklist: docs\QA_FRESH_MACHINE.md
-->
"@.Trim(), 1)

# XML-escape the host path: it can legitimately contain & in a user profile name.
$escaped = [System.Security.SecurityElement]::Escape($sourceFull)
$xml = $xml.Replace("__DCENT_DIST_HOSTFOLDER__", $escaped)

$networkValue = if ($Networking) { "Default" } else { "Disable" }
$xml = $xml.Replace("__DCENT_NETWORKING__", $networkValue)

foreach ($placeholder in @("__DCENT_DIST_HOSTFOLDER__", "__DCENT_NETWORKING__")) {
    if ($xml.Contains($placeholder)) { throw "Template placeholder $placeholder was not substituted." }
}

$outputFull = [System.IO.Path]::GetFullPath($Output)
$outputDir = Split-Path -Parent $outputFull
if (-not (Test-Path -LiteralPath $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}
# Windows Sandbox rejects a UTF-8 BOM in the .wsb.
[System.IO.File]::WriteAllText($outputFull, $xml, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Wrote $outputFull"
Write-Host "  mapped (read-only): $sourceFull -> C:\Users\WDAGUtilityAccount\Desktop\dist"
Write-Host "  networking:         $networkValue"
Write-Host "  checklist:          docs\QA_FRESH_MACHINE.md"

if (-not (Get-Command WindowsSandbox.exe -ErrorAction SilentlyContinue)) {
    Write-Warning "Windows Sandbox is not installed. Enable it with: Enable-WindowsOptionalFeature -Online -FeatureName 'Containers-DisposableClientVM' -All"
}

if ($Start) {
    Start-Process -FilePath $outputFull
}
