#!/usr/bin/env python3
# DCENT_Voice — open-source, local-first voice dictation
# Copyright (c) 2026 D-Central Technologies — decentralized technologies for digital sovereignty
# SPDX-License-Identifier: MIT
"""Single-source release version validation and Windows resource generation."""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION_PATTERN = re.compile(
    r"^(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)"
    r"(?:(?:[-.]?)(?P<stage>a|alpha|b|beta|rc|pre)(?:[.-]?)(?P<serial>\d+))?$",
    re.IGNORECASE,
)


def project_version(root: Path = ROOT) -> str:
    with (root / "pyproject.toml").open("rb") as stream:
        value = tomllib.load(stream)["project"]["version"]
    return normalize_version(str(value))


def normalize_version(value: str) -> str:
    candidate = value.strip().lower()
    if candidate.startswith("v"):
        candidate = candidate[1:]
    match = VERSION_PATTERN.fullmatch(candidate)
    if match is None:
        raise ValueError(f"unsupported release version: {value!r}")
    stage = match.group("stage") or ""
    stage = {"alpha": "a", "beta": "b", "pre": "rc"}.get(stage, stage)
    serial = match.group("serial") or ""
    return f"{match.group('major')}.{match.group('minor')}.{match.group('patch')}{stage}{serial}"


def version_parts(value: str) -> tuple[int, int, int, int]:
    match = VERSION_PATTERN.fullmatch(normalize_version(value))
    assert match is not None
    return (
        int(match.group("major")),
        int(match.group("minor")),
        int(match.group("patch")),
        int(match.group("serial") or 0),
    )


def apple_versions(value: str) -> tuple[str, str]:
    normalized = normalize_version(value)
    match = VERSION_PATTERN.fullmatch(normalized)
    assert match is not None
    marketing = f"{match.group('major')}.{match.group('minor')}.{match.group('patch')}"
    stage = match.group("stage") or ""
    stage_rank = {"a": 100, "b": 200, "rc": 300}.get(stage, 900)
    build_tail = int(match.group("patch")) * 1000 + stage_rank + int(match.group("serial") or 0)
    if build_tail > 9999:
        raise ValueError(f"Apple build version cannot encode patch/stage: {value!r}")
    return marketing, f"{match.group('major')}.{match.group('minor')}.{build_tail}"


def debian_version(value: str) -> str:
    normalized = normalize_version(value)
    match = VERSION_PATTERN.fullmatch(normalized)
    assert match is not None
    base = f"{match.group('major')}.{match.group('minor')}.{match.group('patch')}"
    stage = match.group("stage") or ""
    if not stage:
        return base
    return f"{base}~{stage}{match.group('serial')}"


def _pyinstaller_resource(version: str) -> str:
    parts = version_parts(version)
    tuple_text = ", ".join(str(item) for item in parts)
    return f"""# Generated by scripts/release_version.py from pyproject.toml.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({tuple_text}), prodvers=({tuple_text}), mask=0x3f, flags=0x0,
    OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
      StringStruct('CompanyName', 'D-Central Technologies'),
      StringStruct('FileDescription', 'DCENT_Voice local-first dictation'),
      StringStruct('FileVersion', '{version}'),
      StringStruct('InternalName', 'dcent-voice'),
      StringStruct('LegalCopyright', 'Copyright (c) 2026 D-Central Technologies'),
      StringStruct('OriginalFilename', 'dcent-voice.exe'),
      StringStruct('ProductName', 'DCENT_Voice'),
      StringStruct('ProductVersion', '{version}'),
    ])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ]
)
"""


def _dotnet_props(version: str) -> str:
    numeric = ".".join(str(item) for item in version_parts(version))
    return f"""<!-- Generated by scripts/release_version.py from pyproject.toml. -->
<Project>
  <PropertyGroup>
    <Version>{numeric}</Version>
    <AssemblyVersion>{numeric}</AssemblyVersion>
    <FileVersion>{numeric}</FileVersion>
    <InformationalVersion>{version}</InformationalVersion>
    <Product>DCENT_Voice</Product>
    <Company>D-Central Technologies</Company>
    <AssemblyTitle>DCENT_Voice Setup</AssemblyTitle>
    <Description>DCENT_Voice local-first dictation installer</Description>
    <Copyright>Copyright (c) 2026 D-Central Technologies</Copyright>
  </PropertyGroup>
</Project>
"""


def write_windows_resources(root: Path = ROOT) -> None:
    version = project_version(root)
    (root / "packaging/windows/dcent-voice-version.txt").write_text(
        _pyinstaller_resource(version), encoding="utf-8"
    )
    (root / "packaging/windows/setup-stub/ReleaseVersion.props").write_text(
        _dotnet_props(version), encoding="utf-8"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check-version")
    parser.add_argument("--write-windows-resources", action="store_true")
    parser.add_argument(
        "--format",
        choices=("project", "apple-marketing", "apple-build", "debian"),
        default="project",
    )
    args = parser.parse_args(argv)
    try:
        expected = project_version()
        if args.check_version is not None:
            actual = normalize_version(args.check_version)
            if actual != expected:
                raise ValueError(
                    f"release version mismatch: tag/artifact {actual!r} != project {expected!r}"
                )
        if args.write_windows_resources:
            write_windows_resources()
    except (KeyError, OSError, ValueError) as exc:
        print(f"release version check failed: {exc}", file=sys.stderr)
        return 1
    formatted = {
        "project": expected,
        "apple-marketing": apple_versions(expected)[0],
        "apple-build": apple_versions(expected)[1],
        "debian": debian_version(expected),
    }[args.format]
    print(formatted)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
